/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Comment {
    content: string;
    author: Principal;
    timestamp: Time;
    postId: bigint;
}
export interface User {
    isApproved: boolean;
    name: string;
    role: Role;
    email: string;
    profilePic?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Registration {
    eventId: bigint;
    user: Principal;
    isPaid: boolean;
    timestamp: Time;
}
export interface PostView {
    id: bigint;
    status: PostStatus;
    content: string;
    isPrivateGroup: boolean;
    authorName: string;
    author: Principal;
    likes: Array<Principal>;
    groupMembers: Array<Principal>;
    timestamp: Time;
    category: PostCategory;
    image?: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Event {
    id: bigint;
    status: EventStatus;
    title: string;
    creator: Principal;
    registrationLimit?: bigint;
    date: Time;
    banner?: ExternalBlob;
    description: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Notification {
    notificationType: Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder;
    recipient: Principal;
    isRead: boolean;
    message: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum EventStatus {
    pending = "pending",
    approved = "approved"
}
export enum PostCategory {
    fun = "fun",
    coreTeam = "coreTeam",
    general = "general",
    requirements = "requirements",
    announcements = "announcements",
    membershipCommittee = "membershipCommittee",
    leadershipTeam = "leadershipTeam"
}
export enum PostStatus {
    pending = "pending",
    published = "published"
}
export enum Role {
    lt = "lt",
    mc = "mc",
    elt = "elt",
    member = "member",
    secretaryTreasurer = "secretaryTreasurer",
    vicePresident = "vicePresident",
    rootAdmin = "rootAdmin",
    president = "president"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder {
    roleAssigned = "roleAssigned",
    eventCreated = "eventCreated",
    tenureSwitched = "tenureSwitched",
    accountApproved = "accountApproved",
    announcementPublished = "announcementPublished",
    eventReminder = "eventReminder"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: bigint, content: string): Promise<void>;
    /**
     * / Approve a pending event. Only Root Admin, President, VP, and ST may call this.
     */
    approveEvent(eventId: bigint): Promise<void>;
    approvePost(postId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: Role): Promise<void>;
    createEvent(title: string, description: string, date: Time, banner: ExternalBlob | null, registrationLimit: bigint | null): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(postId: bigint): Promise<Array<Comment>>;
    /**
     * / Get registrations for an event.
     * / Only senior leadership can view the full registration list with payment status.
     */
    getEventRegistrations(eventId: bigint): Promise<Array<Registration>>;
    /**
     * / Returns only approved events to regular users.
     * / Senior leadership (rootAdmin, president, VP, ST) can also see pending events.
     */
    getEvents(): Promise<Array<Event>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyPosts(): Promise<Array<PostView>>;
    getPosts(categoryFilter: PostCategory | null): Promise<Array<PostView>>;
    getUserProfile(user: Principal): Promise<User | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markNotificationsRead(): Promise<void>;
    registerForEvent(eventId: bigint): Promise<void>;
    registerUser(name: string, email: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: User): Promise<void>;
    searchPostsByMember(memberName: string): Promise<Array<PostView>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    startNewTenure(president: Principal, vicePresident: Principal, secretaryTreasurer: Principal, startDate: Time, endDate: Time): Promise<void>;
    submitPost(category: PostCategory, content: string, image: ExternalBlob | null): Promise<void>;
    toggleLike(postId: bigint): Promise<void>;
    /**
     * / Toggle the isPaid flag on an event registration.
     * / Only Root Admin, President, Vice President, and Secretary Treasurer may call this.
     */
    togglePaid(eventId: bigint, user: Principal): Promise<void>;
    uploadProfilePic(image: ExternalBlob): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Event as _Event, EventStatus as _EventStatus, ExternalBlob as _ExternalBlob, Notification as _Notification, PostCategory as _PostCategory, PostStatus as _PostStatus, PostView as _PostView, Role as _Role, Time as _Time, User as _User, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async approveEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveEvent(arg0);
            return result;
        }
    }
    async approvePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePost(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: Time, arg3: ExternalBlob | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getEventRegistrations(arg0: bigint): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventRegistrations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventRegistrations(arg0);
            return result;
        }
    }
    async getEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPosts(): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPosts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPosts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(arg0: PostCategory | null): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async registerForEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_User_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_User_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPostsByMember(arg0: string): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPostsByMember(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPostsByMember(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async startNewTenure(arg0: Principal, arg1: Principal, arg2: Principal, arg3: Time, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewTenure(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewTenure(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitPost(arg0: PostCategory, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPost(to_candid_PostCategory_n41(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPost(to_candid_PostCategory_n41(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async toggleLike(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async togglePaid(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePaid(arg0, arg1);
            return result;
        }
    }
    async uploadProfilePic(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePic(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePic(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Notification_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PostCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostCategory): PostCategory {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_PostView_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostView): Promise<PostView> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    name: string;
    role: _Role;
    email: string;
    profilePic: [] | [_ExternalBlob];
}): Promise<{
    isApproved: boolean;
    name: string;
    role: Role;
    email: string;
    profilePic?: ExternalBlob;
}> {
    return {
        isApproved: value.isApproved,
        name: value.name,
        role: from_candid_Role_n18(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profilePic: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.profilePic))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    title: string;
    creator: Principal;
    registrationLimit: [] | [bigint];
    date: _Time;
    banner: [] | [_ExternalBlob];
    description: string;
}): Promise<{
    id: bigint;
    status: EventStatus;
    title: string;
    creator: Principal;
    registrationLimit?: bigint;
    date: Time;
    banner?: ExternalBlob;
    description: string;
}> {
    return {
        id: value.id,
        status: from_candid_EventStatus_n27(_uploadFile, _downloadFile, value.status),
        title: value.title,
        creator: value.creator,
        registrationLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.registrationLimit)),
        date: value.date,
        banner: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.banner)),
        description: value.description
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationType: {
        roleAssigned: null;
    } | {
        eventCreated: null;
    } | {
        tenureSwitched: null;
    } | {
        accountApproved: null;
    } | {
        announcementPublished: null;
    } | {
        eventReminder: null;
    };
    recipient: Principal;
    isRead: boolean;
    message: string;
    timestamp: _Time;
}): {
    notificationType: Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder;
    recipient: Principal;
    isRead: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        notificationType: from_candid_variant_n32(_uploadFile, _downloadFile, value.notificationType),
        recipient: value.recipient,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PostStatus;
    content: string;
    isPrivateGroup: boolean;
    authorName: string;
    author: Principal;
    likes: Array<Principal>;
    groupMembers: Array<Principal>;
    timestamp: _Time;
    category: _PostCategory;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    status: PostStatus;
    content: string;
    isPrivateGroup: boolean;
    authorName: string;
    author: Principal;
    likes: Array<Principal>;
    groupMembers: Array<Principal>;
    timestamp: Time;
    category: PostCategory;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_PostStatus_n36(_uploadFile, _downloadFile, value.status),
        content: value.content,
        isPrivateGroup: value.isPrivateGroup,
        authorName: value.authorName,
        author: value.author,
        likes: value.likes,
        groupMembers: value.groupMembers,
        timestamp: value.timestamp,
        category: from_candid_PostCategory_n38(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n46(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lt: null;
} | {
    mc: null;
} | {
    elt: null;
} | {
    member: null;
} | {
    secretaryTreasurer: null;
} | {
    vicePresident: null;
} | {
    rootAdmin: null;
} | {
    president: null;
}): Role {
    return "lt" in value ? Role.lt : "mc" in value ? Role.mc : "elt" in value ? Role.elt : "member" in value ? Role.member : "secretaryTreasurer" in value ? Role.secretaryTreasurer : "vicePresident" in value ? Role.vicePresident : "rootAdmin" in value ? Role.rootAdmin : "president" in value ? Role.president : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): EventStatus {
    return "pending" in value ? EventStatus.pending : "approved" in value ? EventStatus.approved : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roleAssigned: null;
} | {
    eventCreated: null;
} | {
    tenureSwitched: null;
} | {
    accountApproved: null;
} | {
    announcementPublished: null;
} | {
    eventReminder: null;
}): Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder {
    return "roleAssigned" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.roleAssigned : "eventCreated" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.eventCreated : "tenureSwitched" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.tenureSwitched : "accountApproved" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.accountApproved : "announcementPublished" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.announcementPublished : "eventReminder" in value ? Variant_roleAssigned_eventCreated_tenureSwitched_accountApproved_announcementPublished_eventReminder.eventReminder : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    published: null;
}): PostStatus {
    return "pending" in value ? PostStatus.pending : "published" in value ? PostStatus.published : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fun: null;
} | {
    coreTeam: null;
} | {
    general: null;
} | {
    requirements: null;
} | {
    announcements: null;
} | {
    membershipCommittee: null;
} | {
    leadershipTeam: null;
}): PostCategory {
    return "fun" in value ? PostCategory.fun : "coreTeam" in value ? PostCategory.coreTeam : "general" in value ? PostCategory.general : "requirements" in value ? PostCategory.requirements : "announcements" in value ? PostCategory.announcements : "membershipCommittee" in value ? PostCategory.membershipCommittee : "leadershipTeam" in value ? PostCategory.leadershipTeam : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostView>): Promise<Array<PostView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostView_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n44(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PostCategory_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): _PostCategory {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_User_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): Promise<_User> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory | null): [] | [_PostCategory] {
    return value === null ? candid_none() : candid_some(to_candid_PostCategory_n41(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    name: string;
    role: Role;
    email: string;
    profilePic?: ExternalBlob;
}): Promise<{
    isApproved: boolean;
    name: string;
    role: _Role;
    email: string;
    profilePic: [] | [_ExternalBlob];
}> {
    return {
        isApproved: value.isApproved,
        name: value.name,
        role: to_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.profilePic)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    lt: null;
} | {
    mc: null;
} | {
    elt: null;
} | {
    member: null;
} | {
    secretaryTreasurer: null;
} | {
    vicePresident: null;
} | {
    rootAdmin: null;
} | {
    president: null;
} {
    return value == Role.lt ? {
        lt: null
    } : value == Role.mc ? {
        mc: null
    } : value == Role.elt ? {
        elt: null
    } : value == Role.member ? {
        member: null
    } : value == Role.secretaryTreasurer ? {
        secretaryTreasurer: null
    } : value == Role.vicePresident ? {
        vicePresident: null
    } : value == Role.rootAdmin ? {
        rootAdmin: null
    } : value == Role.president ? {
        president: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): {
    fun: null;
} | {
    coreTeam: null;
} | {
    general: null;
} | {
    requirements: null;
} | {
    announcements: null;
} | {
    membershipCommittee: null;
} | {
    leadershipTeam: null;
} {
    return value == PostCategory.fun ? {
        fun: null
    } : value == PostCategory.coreTeam ? {
        coreTeam: null
    } : value == PostCategory.general ? {
        general: null
    } : value == PostCategory.requirements ? {
        requirements: null
    } : value == PostCategory.announcements ? {
        announcements: null
    } : value == PostCategory.membershipCommittee ? {
        membershipCommittee: null
    } : value == PostCategory.leadershipTeam ? {
        leadershipTeam: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
