/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'lt' : IDL.Null,
  'mc' : IDL.Null,
  'elt' : IDL.Null,
  'member' : IDL.Null,
  'secretaryTreasurer' : IDL.Null,
  'vicePresident' : IDL.Null,
  'rootAdmin' : IDL.Null,
  'president' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const User = IDL.Record({
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const Registration = IDL.Record({
  'eventId' : IDL.Nat,
  'user' : IDL.Principal,
  'isPaid' : IDL.Bool,
  'timestamp' : Time,
});
export const EventStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'registrationLimit' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'banner' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
});
export const Notification = IDL.Record({
  'notificationType' : IDL.Variant({
    'roleAssigned' : IDL.Null,
    'eventCreated' : IDL.Null,
    'tenureSwitched' : IDL.Null,
    'accountApproved' : IDL.Null,
    'announcementPublished' : IDL.Null,
    'eventReminder' : IDL.Null,
  }),
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PostStatus = IDL.Variant({
  'pending' : IDL.Null,
  'published' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'fun' : IDL.Null,
  'coreTeam' : IDL.Null,
  'general' : IDL.Null,
  'requirements' : IDL.Null,
  'announcements' : IDL.Null,
  'membershipCommittee' : IDL.Null,
  'leadershipTeam' : IDL.Null,
});
export const PostView = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'content' : IDL.Text,
  'isPrivateGroup' : IDL.Bool,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'groupMembers' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'category' : PostCategory,
  'image' : IDL.Opt(ExternalBlob),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveEvent' : IDL.Func([IDL.Nat], [], []),
  'approvePost' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, Role], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getEventRegistrations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getPendingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPendingPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getPendingUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
      ['query'],
    ),
  'getPosts' : IDL.Func(
      [IDL.Opt(PostCategory)],
      [IDL.Vec(PostView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'registerForEvent' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'searchPostsByMember' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'startNewTenure' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Principal, Time, Time],
      [],
      [],
    ),
  'submitPost' : IDL.Func(
      [PostCategory, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'toggleLike' : IDL.Func([IDL.Nat], [], []),
  'togglePaid' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'uploadProfilePic' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'lt' : IDL.Null,
    'mc' : IDL.Null,
    'elt' : IDL.Null,
    'member' : IDL.Null,
    'secretaryTreasurer' : IDL.Null,
    'vicePresident' : IDL.Null,
    'rootAdmin' : IDL.Null,
    'president' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const User = IDL.Record({
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const Registration = IDL.Record({
    'eventId' : IDL.Nat,
    'user' : IDL.Principal,
    'isPaid' : IDL.Bool,
    'timestamp' : Time,
  });
  const EventStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'registrationLimit' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'banner' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
  });
  const Notification = IDL.Record({
    'notificationType' : IDL.Variant({
      'roleAssigned' : IDL.Null,
      'eventCreated' : IDL.Null,
      'tenureSwitched' : IDL.Null,
      'accountApproved' : IDL.Null,
      'announcementPublished' : IDL.Null,
      'eventReminder' : IDL.Null,
    }),
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PostStatus = IDL.Variant({
    'pending' : IDL.Null,
    'published' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'fun' : IDL.Null,
    'coreTeam' : IDL.Null,
    'general' : IDL.Null,
    'requirements' : IDL.Null,
    'announcements' : IDL.Null,
    'membershipCommittee' : IDL.Null,
    'leadershipTeam' : IDL.Null,
  });
  const PostView = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'content' : IDL.Text,
    'isPrivateGroup' : IDL.Bool,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'groupMembers' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'category' : PostCategory,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveEvent' : IDL.Func([IDL.Nat], [], []),
    'approvePost' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, Role], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getEventRegistrations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getMyRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getPendingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPendingPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getPendingUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
        ['query'],
      ),
    'getPosts' : IDL.Func(
        [IDL.Opt(PostCategory)],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'registerForEvent' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'searchPostsByMember' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'startNewTenure' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Principal, Time, Time],
        [],
        [],
      ),
    'submitPost' : IDL.Func(
        [PostCategory, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'toggleLike' : IDL.Func([IDL.Nat], [], []),
    'togglePaid' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'uploadProfilePic' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };