/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface Event {
  'id' : bigint,
  'status' : EventStatus,
  'title' : string,
  'creator' : Principal,
  'registrationLimit' : [] | [bigint],
  'date' : Time,
  'banner' : [] | [ExternalBlob],
  'description' : string,
}
export type EventStatus = { 'pending' : null } |
  { 'approved' : null };
export type ExternalBlob = Uint8Array;
export interface Notification {
  'notificationType' : { 'roleAssigned' : null } |
    { 'eventCreated' : null } |
    { 'tenureSwitched' : null } |
    { 'accountApproved' : null } |
    { 'announcementPublished' : null } |
    { 'eventReminder' : null },
  'recipient' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type PostCategory = { 'fun' : null } |
  { 'coreTeam' : null } |
  { 'general' : null } |
  { 'requirements' : null } |
  { 'announcements' : null } |
  { 'membershipCommittee' : null } |
  { 'leadershipTeam' : null };
export type PostStatus = { 'pending' : null } |
  { 'published' : null };
export interface PostView {
  'id' : bigint,
  'status' : PostStatus,
  'content' : string,
  'isPrivateGroup' : boolean,
  'authorName' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'groupMembers' : Array<Principal>,
  'timestamp' : Time,
  'category' : PostCategory,
  'image' : [] | [ExternalBlob],
}
export interface Registration {
  'eventId' : bigint,
  'user' : Principal,
  'isPaid' : boolean,
  'timestamp' : Time,
}
export type Role = { 'lt' : null } |
  { 'mc' : null } |
  { 'elt' : null } |
  { 'member' : null } |
  { 'secretaryTreasurer' : null } |
  { 'vicePresident' : null } |
  { 'rootAdmin' : null } |
  { 'president' : null };
export type Time = bigint;
export interface User {
  'isApproved' : boolean,
  'name' : string,
  'role' : Role,
  'description' : string,
  'email' : string,
  'companyName' : string,
  'profilePic' : [] | [ExternalBlob],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'approveEvent' : ActorMethod<[bigint], undefined>,
  /**
   * / Approve or reject a pending user registration.
   * / Permitted callers: AccessControl admins (#admin role) OR executive core/master admin.
   */
  'approveOrRejectUser' : ActorMethod<
    [Principal, ApprovalStatus],
    {
      'updatedUsers' : Array<[Principal, User]>,
      'approvals' : Array<UserApprovalInfo>,
    }
  >,
  'approvePost' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, Role], undefined>,
  'createEvent' : ActorMethod<
    [string, string, Time, [] | [ExternalBlob], [] | [bigint]],
    undefined
  >,
  'deleteComment' : ActorMethod<[bigint, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, User]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getEventRegistrations' : ActorMethod<[bigint], Array<Registration>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyPosts' : ActorMethod<[], Array<PostView>>,
  'getMyRegistrations' : ActorMethod<[], Array<Registration>>,
  /**
   * / View pending approvals.
   * / Permitted callers: AccessControl admins (#admin role) OR executive core / master admin.
   */
  'getPendingApprovals' : ActorMethod<
    [],
    {
      'users' : Array<[Principal, User]>,
      'approvals' : Array<UserApprovalInfo>,
    }
  >,
  'getPendingEvents' : ActorMethod<[], Array<Event>>,
  'getPendingPosts' : ActorMethod<[], Array<PostView>>,
  /**
   * / View pending (unapproved) users.
   * / Permitted callers: AccessControl admins (#admin role) OR executive core / master admin.
   */
  'getPendingUsers' : ActorMethod<[], Array<[Principal, User]>>,
  'getPosts' : ActorMethod<[[] | [PostCategory]], Array<PostView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'registerForEvent' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'searchPostsByMember' : ActorMethod<[string], Array<PostView>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'startNewTenure' : ActorMethod<
    [Principal, Principal, Principal, Time, Time],
    undefined
  >,
  'submitPost' : ActorMethod<
    [PostCategory, string, [] | [ExternalBlob]],
    undefined
  >,
  'toggleLike' : ActorMethod<[bigint], undefined>,
  'togglePaid' : ActorMethod<[bigint, Principal], undefined>,
  'uploadProfilePic' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];